/**
 * Small SPA router for MovieID without pulling in react-router.
 *
 * URL shape:
 *   /                                      -> Movie ID
 *   /tiktok                                -> TikTok Explorer
 *   /tiktok/saved                          -> saved TikTok lists
 *   /tiktok/saved/playlist/<slug>          -> saved playlist or collection
 *   /tiktok/saved/channel/<slug>           -> saved channel feed
 *   /tiktok/post/<slug>                    -> saved individual post
 *   /tiktok?tab=collection&url=<encoded>   -> unsaved playlist/collection/video
 *   /tiktok?tab=channel&url=<encoded>      -> unsaved profile feed
 *   /youtube                               -> YouTube Niche Radar
 *   /niches                                -> top-level niche index
 *   /niches/<top>                          -> sub-niches for a top-level niche
 *   /niches/<top>/<sub>                    -> MSNs for a sub-niche
 *   /niches/<top>/<sub>/<msn>              -> MSN detail
 *   /feed                                  -> YouTube channel feed
 *   /channels                              -> YouTube Channel Management
 *   /compile                               -> Long-form compilation studio
 *   /automation                            -> TikTok to YouTube automation agents
 *   /rewriter                              -> AI Rewriter
 *   /tts                                   -> Text to Speech
 */

export type MainView = "movie" | "tiktok" | "youtube" | "niches" | "feed" | "channels" | "publish" | "compile" | "automation" | "rewriter" | "tts";
export type ListTab = "collection" | "channel";
export type TikTokSection = "analyze" | "saved";

export interface TikTokDeepLink {
  view: MainView;
  section?: TikTokSection;
  tab?: ListTab;
  /** Fully-qualified TikTok URL already passed through `canonicalBareTikTokProfileUrl` when a profile. */
  url?: string;
  slug?: string;
  nichePath?: string[];
  postSlug?: string;
}

function isMainView(v: string | null | undefined): v is MainView {
  return v === "movie" || v === "tiktok" || v === "youtube" || v === "niches" || v === "feed" || v === "channels" || v === "publish" || v === "compile" || v === "automation" || v === "rewriter" || v === "tts";
}

function isListTab(v: string | null | undefined): v is ListTab {
  return v === "collection" || v === "channel";
}

function readTikTokQuery(): Pick<TikTokDeepLink, "tab" | "url"> {
  const params = new URLSearchParams(window.location.search);
  const rawTab = params.get("tab");
  return {
    tab: isListTab(rawTab) ? rawTab : undefined,
    url: (params.get("url") || "").trim() || undefined,
  };
}

export function readDeepLink(): TikTokDeepLink {
  if (typeof window === "undefined") return { view: "movie" };

  const pathParts = window.location.pathname.split("/").filter(Boolean);

  if (pathParts[0] === "tts") {
    return { view: "tts" };
  }

  if (pathParts[0] === "rewriter") {
    return { view: "rewriter" };
  }

  if (pathParts[0] === "youtube") {
    return { view: "youtube" };
  }

  if (pathParts[0] === "niches") {
    const nichePath = pathParts.slice(1).map((part) => decodeURIComponent(part)).filter(Boolean);
    return { view: "niches", slug: nichePath[0], nichePath };
  }

  if (pathParts[0] === "feed") {
    return { view: "feed" };
  }

  if (pathParts[0] === "channels") {
    return { view: "channels" };
  }

  if (pathParts[0] === "publish") {
    return { view: "channels" };
  }

  if (pathParts[0] === "compile") {
    return { view: "compile" };
  }

  if (pathParts[0] === "automation") {
    return { view: "automation", slug: pathParts[1] ? decodeURIComponent(pathParts[1]) : undefined };
  }

  if (pathParts[0] === "tiktok") {
    if (pathParts[1] === "saved") {
      if (pathParts[2] === "playlist" && pathParts[3]) {
        return {
          view: "tiktok",
          section: "analyze",
          tab: "collection",
          slug: decodeURIComponent(pathParts[3]),
        };
      }
      if (pathParts[2] === "channel" && pathParts[3]) {
        return {
          view: "tiktok",
          section: "analyze",
          tab: "channel",
          slug: decodeURIComponent(pathParts[3]),
        };
      }
      return { view: "tiktok", section: "saved" };
    }
    // Backward compatibility for saved links generated by older builds.
    if (pathParts[1] === "playlist" && pathParts[2]) {
      return {
        view: "tiktok",
        section: "analyze",
        tab: "collection",
        slug: decodeURIComponent(pathParts[2]),
      };
    }
    if (pathParts[1] === "channel" && pathParts[2]) {
      return {
        view: "tiktok",
        section: "analyze",
        tab: "channel",
        slug: decodeURIComponent(pathParts[2]),
      };
    }
    if (pathParts[1] === "post" && pathParts[2]) {
      return {
        view: "tiktok",
        section: "analyze",
        postSlug: decodeURIComponent(pathParts[2]),
      };
    }
    return { view: "tiktok", section: "analyze", ...readTikTokQuery() };
  }

  // Backward compatibility for links generated by older builds.
  if (pathParts[0] === "playlist" && pathParts[1]) {
    return {
      view: "tiktok",
      section: "analyze",
      tab: "collection",
      slug: decodeURIComponent(pathParts[1]),
    };
  }
  if (pathParts[0] === "channel" && pathParts[1]) {
    return {
      view: "tiktok",
      section: "analyze",
      tab: "channel",
      slug: decodeURIComponent(pathParts[1]),
    };
  }
  if (pathParts[0] === "post" && pathParts[1]) {
    return {
      view: "tiktok",
      section: "analyze",
      postSlug: decodeURIComponent(pathParts[1]),
    };
  }

  const params = new URLSearchParams(window.location.search);
  const rawView = params.get("view");
  const view: MainView = isMainView(rawView) ? rawView : "movie";
  return {
    view,
    section: view === "tiktok" ? "analyze" : undefined,
    ...readTikTokQuery(),
  };
}

/**
 * Push / replace the URL without reloading. Safe to call with the same value:
 * we skip when the resulting href matches the current one so browser history
 * stays meaningful.
 */
export function writeDeepLink(link: TikTokDeepLink, replace = false): void {
  if (typeof window === "undefined") return;

  let href = "/";
  if (link.view === "tts") {
    href = "/tts";
  } else if (link.view === "rewriter") {
    href = "/rewriter";
  } else if (link.view === "automation") {
    href = link.slug ? `/automation/${encodeURIComponent(link.slug)}` : "/automation";
  } else if (link.view === "compile") {
    href = "/compile";
  } else if (link.view === "publish") {
    href = "/publish";
  } else if (link.view === "channels") {
    href = "/channels";
  } else if (link.view === "feed") {
    href = "/feed";
  } else if (link.view === "youtube") {
    href = "/youtube";
  } else if (link.view === "niches") {
    const nichePath = link.nichePath?.length ? link.nichePath : link.slug ? [link.slug] : [];
    href = nichePath.length ? `/niches/${nichePath.map((part) => encodeURIComponent(part)).join("/")}` : "/niches";
  } else if (link.view === "tiktok") {
    if (link.section === "saved") {
      href = "/tiktok/saved";
    } else if (link.postSlug) {
      href = `/tiktok/post/${encodeURIComponent(link.postSlug)}`;
    } else if (link.slug && link.tab) {
      const prefix = link.tab === "channel" ? "channel" : "playlist";
      href = `/tiktok/saved/${prefix}/${encodeURIComponent(link.slug)}`;
    } else {
      const params = new URLSearchParams();
      if (link.tab) params.set("tab", link.tab);
      if (link.url) params.set("url", link.url);
      const qs = params.toString();
      href = `/tiktok${qs ? `?${qs}` : ""}`;
    }
  }

  const current = `${window.location.pathname}${window.location.search}`;
  if (href === current) return;
  if (replace) window.history.replaceState(null, "", href);
  else window.history.pushState(null, "", href);
  window.dispatchEvent(new PopStateEvent("popstate"));
}
